#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT

export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_DIY_PORT
export HOST=$OPENSHIFT_DIY_IP
export HOME=$OPENSHIFT_DATA_DIR
export LEIN_JVM_OPTS=-Duser.home=$HOME

cd $OPENSHIFT_REPO_DIR
nohup $OPENSHIFT_REPO_DIR/bin/lein trampoline run 2>&1 | /usr/bin/logshifter -tag diy &
